In [2]:
import pandas as pd
import numpy as np

In [3]:
# mount the drive
from google.colab import drive
drive.mount('/content/drive')

# change directory
%cd drive/MyDrive/Final Project

Mounted at /content/drive
/content/drive/MyDrive/Final Project

In [4]:
movies = pd.read_csv("data/movies_metadata.csv")

<ipython-input-4-f8e68357cbad>:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  movies = pd.read_csv("data/movies_metadata.csv")

In [5]:
movies.head(2)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0

In [6]:
movies = movies[["genres","overview","title"]]

In [7]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   genres    45466 non-null  object
 1   overview  44512 non-null  object
 2   title     45460 non-null  object
dtypes: object(3)
memory usage: 1.0+ MB

In [8]:
movies.head()

,genres,overview,title
0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","Led by Woody, Andy's toys live happily in his ...",Toy Story
1,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",When siblings Judy and Peter discover an encha...,Jumanji
2,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",A family wedding reignites the ancient feud be...,Grumpier Old Men
3,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","Cheated on, mistreated and stepped on, the wom...",Waiting to Exhale
4,"[{'id': 35, 'name': 'Comedy'}]",Just when George Banks has recovered from his ...,Father of the Bride Part II

In [9]:
from ast import literal_eval

In [10]:
def gender_mining(row):

    row = literal_eval(row)

    genres = []
    for i in row:
        genres.append(i["name"])

    return str(genres)

In [11]:
movies["genre_list"] = movies["genres"].apply(gender_mining)

In [12]:
movies.index=movies.title.values

In [13]:
movies = movies[["genre_list","overview"]]
movies.dropna(inplace=True)
movies = movies[movies["genre_list"]!="[]"]
movies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 42327 entries, Toy Story to Betrayal
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   genre_list  42327 non-null  object
 1   overview    42327 non-null  object
dtypes: object(2)
memory usage: 992.0+ KB

<ipython-input-13-922480a67e91>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies.dropna(inplace=True)

In [14]:
movies.head()

,genre_list,overview
Toy Story,"['Animation', 'Comedy', 'Family']","Led by Woody, Andy's toys live happily in his ..."
Jumanji,"['Adventure', 'Fantasy', 'Family']",When siblings Judy and Peter discover an encha...
Grumpier Old Men,"['Romance', 'Comedy']",A family wedding reignites the ancient feud be...
Waiting to Exhale,"['Comedy', 'Drama', 'Romance']","Cheated on, mistreated and stepped on, the wom..."
Father of the Bride Part II,['Comedy'],Just when George Banks has recovered from his ...

## Narrowing down to only couple of most distinguishable genres

In [15]:
genres = ['Fantasy','Horror','Romance','Action','Family']

In [16]:
def filter(genre_list):

  gens = literal_eval(genre_list)

  return set(gens).issubset(set(genres))

In [17]:
movies["mask"] = movies["genre_list"].apply(filter)

In [ ]:
movies.head()

In [19]:
movies_narrowed = movies[movies["mask"]]
movies_narrowed.head()

,genre_list,overview,mask
Mortal Kombat,"['Action', 'Fantasy']",For nine generations an evil sorcerer has been...,True
The Neverending Story III: Escape from Fantasia,['Fantasy'],A young boy must restore order when a group of...,True
Interview with the Vampire,"['Horror', 'Romance']","A vampire relates his epic life story of love,...",True
Beyond Bedlam,['Horror'],An experiment gone awry places a neurologist (...,True
Wolf,['Fantasy'],Publisher Will Randall becomes a werewolf and ...,True

In [20]:
movies_narrowed = movies_narrowed[["genre_list","overview"]]

In [21]:
movies_narrowed.to_csv("data/movies_genre&overview.csv")